### ISSUE TITLE
Add recent / scheduled talks

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/quantum-wednesday#23]
Add recent talk (@Misty-W @jordandsullivan can you help?) plus add scheduled talks that are in the calendar.

**Comment by Misty-W** [comment]
I wasn't able to attend, maybe @jordandsullivan has the info for this one. 

I'll add the upcoming ones.

**Comment by jordandsullivan** [comment]
I wonder if we could add some automation from air table to update this, and possibly send an email asking for folks slides afterwards?

**Comment by natestemen** [comment]
Yeah I was looking for an option to do that when I set this repo up. I was not able to find a  way for airtable to write to a GitHub repo directly. There is [this](https://www.airtable.com/integrations/github) integration, but it doesn't write to repos. Looks like there is functionality to open issues, maybe?

Might be more pain (i.e. maintenance) than it's worth since it's relatively quick work.

**Comment by Misty-W** [comment]
thanks @natestemen! I might poke around the GitHub integration a bit.
